=== alvesjnr/opentrials/repository/xml/opentrials.dtd
<!-- ===========================================================================
File: opentrials.dtd

OpenTrials: Latin-American and Caribbean Clinical Trial Record XML DTD
DTD Version 1.0: 2010-03-01

This DTD depends on the opentrials-vocabularies.mod definitions file.

See:
http://reddes.bvsalud.org/projects/clinical-trials/wiki/RegistrationDataModel

Partially based on the WHO ICTRP XML DTD, http://www.who.int/ictrp
DTD Version 1.0: 2008-04-23 (with changes up to and including 2008-09-15)
Most element names are the same. Structure is different, with more validation
in the form of attribute enumerations. Also, this is intended to represent a
single trial record.

Comments:
  - "formset n/9" refer to each of the 9 trial submission forms
  - "TRDS n (x..y)": field number in the ICTRP Trial Registration Data Set
                     (x..y) indicate element multiplicity in UML notation
=========================================================================== -->

<!ENTITY % vocabularies SYSTEM "opentrials-vocabularies.mod">
%vocabularies;

<!ELEMENT trials (trial+)>

<!ELEMENT trial (trial_identification, sponsors_and_support, health_conditions,
          interventions, recruitment, study, outcomes, contacts, secondary_ids?,
          references?, staff_note?, translation*)>
    <!-- trial record must have explicit attribute type="interventional"
         in preparation for eventual support for observational studies -->
    <!ATTLIST trial
        status (%trialstatus.options;) #REQUIRED
        date_registration CDATA #REQUIRED
        created CDATA #IMPLIED
        updated CDATA #IMPLIED
    >

    <!-- formset 1/9 -->
    <!ELEMENT trial_identification (trial_id?, utrn?, reg_name?, public_title?,
                    acronym?, acronym_expansion?, scientific_title, scientific_acronym?,
                    scientific_acronym_expansion?)>

    <!ELEMENT trial_id (#PCDATA)>                              <!--TRDS 1 (0..1)-->
    <!ELEMENT utrn (#PCDATA)>                                    <!--TRDS 3 (0..1)-->
    <!ELEMENT reg_name (#PCDATA)>
    <!ELEMENT public_title (#PCDATA)>                           <!--TRDS 9a (0..1)-->
    <!ELEMENT acronym (#PCDATA)>                                <!--TRDS 9b (0..1)-->
    <!ELEMENT acronym_expansion (#PCDATA)>                     <!--TRDS 10b (0..1)-->
    <!ELEMENT scientific_title (#PCDATA)>                       <!--TRDS 10a (1)-->
    <!ELEMENT scientific_acronym (#PCDATA)>                     <!--TRDS 10b (0..1)-->
    <!ELEMENT scientific_acronym_expansion (#PCDATA)>                     <!--TRDS 10b (0..1)-->

    <!ELEMENT secondary_ids (secondary_id+)>
        <!ELEMENT secondary_id (sec_id, issuing_authority)>
            <!ELEMENT sec_id (#PCDATA)>                         <!--TRDS 3a (0..*)-->
            <!ELEMENT issuing_authority (#PCDATA)>              <!--TRDS 3b (0..*)-->

    <!-- formset 2/9 -->
    <!ELEMENT sponsors_and_support (primary_sponsor, secondary_sponsor*, source_support*)>
    <!ELEMENT primary_sponsor (name, address?)>                 <!--TRDS 5 (1)-->
        <!ATTLIST primary_sponsor
            country_code (%country.options;) #REQUIRED>
    <!ELEMENT secondary_sponsor (name, address?)>               <!--TRDS 6 (0..*)-->
        <!ATTLIST secondary_sponsor
            country_code (%country.options;) #REQUIRED>
    <!ELEMENT source_support (name, address?)>                  <!--TRDS 4 (0..*)-->
        <!ATTLIST source_support
            country_code (%country.options;) #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (#PCDATA)>

    <!-- formset 3/9 -->
    <!ELEMENT health_conditions (hc_code*, keyword*, freetext?)>
        <!ELEMENT freetext (#PCDATA)>                               <!--TRDS 12a, 13a (0..1)-->
        <!ELEMENT hc_code (#PCDATA)>                                <!--TRDS 12b (0..*)-->
            <!ATTLIST hc_code
                vocabulary (%vocabulary.options;) #IMPLIED
                version CDATA #IMPLIED>
        <!ELEMENT keyword (#PCDATA)>                                <!--TRDS 12c, 13c (0..*)-->
            <!ATTLIST keyword
                vocabulary (%vocabulary.options;) #IMPLIED
                version CDATA #IMPLIED>

    <!-- formset 4/9 -->
    <!ELEMENT interventions (i_code*, keyword*, freetext?)>           <!--TRDS 12a (0..1)-->
        <!ELEMENT i_code (#PCDATA)>                               <!--TRDS 12b (0..*)-->
            <!ATTLIST i_code
                value (%interventioncode.options;) #IMPLIED>

    <!-- formset 5/9 -->
    <!ELEMENT recruitment (recruitment_country+,
                           inclusion_criteria,
                           exclusion_criteria?,
                           gender?,
                           agemin?,
                           agemax?,
                           date_enrolment_anticipated?,
                           date_enrolment_actual?,
                           target_size?)>
        <!ATTLIST recruitment
            study_status (%studystatus.options;) #REQUIRED>

        <!ELEMENT recruitment_country EMPTY>                          <!--TRDS 11 (1..*)-->
            <!ATTLIST recruitment_country
                value (%country.options;) #REQUIRED>
        <!ELEMENT inclusion_criteria (#PCDATA)>                       <!--TRDS 14a (1)-->
        <!ELEMENT exclusion_criteria (#PCDATA)>                       <!--TRDS 14e (0..1)-->
        <!ELEMENT gender EMPTY>                                       <!--TRDS 14b (0..1)-->
            <!ATTLIST gender
                value (%gender.options;) #REQUIRED>
        <!ELEMENT agemin EMPTY>                                   <!--TRDS 14c (0..1)-->
            <!ATTLIST agemin value CDATA #REQUIRED>
            <!ATTLIST agemin unit (%ageunit.options;) #IMPLIED>
        <!ELEMENT agemax EMPTY>                                   <!--TRDS 14d (0..1)-->
            <!ATTLIST agemax value CDATA #REQUIRED>
            <!ATTLIST agemax unit (%ageunit.options;) #IMPLIED>
        <!ELEMENT date_enrolment_anticipated EMPTY> <!--ISO-8601 date format: YYYY-MM-DD-->
            <!ATTLIST date_enrolment_anticipated
                start CDATA #IMPLIED
                end CDATA #IMPLIED
            >
        <!ELEMENT date_enrolment_actual EMPTY>      <!--ISO-8601 date format: YYYY-MM-DD-->
            <!ATTLIST date_enrolment_actual
                start CDATA #IMPLIED
                end CDATA #IMPLIED
            >
        <!ELEMENT target_size (#PCDATA)>

    <!-- formset 6/9 -->
    <!ELEMENT study (study_design, type?, phase, purpose, intervention_assignment,
                masking, allocation)>
        <!ATTLIST study
            expanded_access_program (yes|no) #IMPLIED
            number_of_arms NMTOKEN #IMPLIED
        >
        <!ELEMENT study_design (#PCDATA)>
        <!ELEMENT type EMPTY>                                    <!--TRDS 15c (0..1)-->
            <!ATTLIST type value (%study_type.options;) #REQUIRED>
        <!ELEMENT phase EMPTY>
            <!ATTLIST phase value (%phase.options;) #REQUIRED>
        <!ELEMENT purpose EMPTY>
            <!ATTLIST purpose value (%purpose.options;) #REQUIRED>
        <!ELEMENT intervention_assignment EMPTY>
            <!ATTLIST intervention_assignment value (%assignment.options;) #REQUIRED>
        <!ELEMENT masking EMPTY>
            <!ATTLIST masking value (%masking.options;) #REQUIRED>
        <!ELEMENT allocation EMPTY>
            <!ATTLIST allocation value (%allocation.options;) #REQUIRED>

    <!-- formset 7/9 -->
    <!ELEMENT outcomes (primary_outcome+, secondary_outcome*)>
    <!ELEMENT primary_outcome (#PCDATA)>
    <!ELEMENT secondary_outcome (#PCDATA)>

    <!-- formset 8/9 -->
    <!ELEMENT contacts (person+, public_contact+, scientific_contact+, site_contact*)>
    <!ELEMENT public_contact EMPTY>
        <!ATTLIST public_contact
            person CDATA #REQUIRED>
    <!ELEMENT scientific_contact EMPTY>
        <!ATTLIST scientific_contact
            person CDATA #REQUIRED>
    <!ELEMENT site_contact EMPTY>
        <!ATTLIST site_contact
            person CDATA #REQUIRED>

    <!ELEMENT person (firstname,middlename?,lastname,address,city,zip,telephone+,email,affiliation)>
        <!ATTLIST person
            pid CDATA #REQUIRED
            country_code (%country.options;) #REQUIRED>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT middlename (#PCDATA)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT zip (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT affiliation (#PCDATA)>

    <!-- formset 9/9 -->
    <!ELEMENT references (link*)>
        <!ELEMENT link (#PCDATA)>
            <!ATTLIST link url CDATA #REQUIRED>

    <!ELEMENT staff_note (#PCDATA)>

    <!ELEMENT translation (public_title?, acronym?, acronym_expansion?, scientific_title,
                           scientific_acronym?, scientific_acronym_expansion?, hc_freetext?,
                           i_freetext?, inclusion_criteria?, exclusion_criteria?, study_design?)>
        <!ATTLIST translation lang CDATA #REQUIRED>
        <!ELEMENT hc_freetext (#PCDATA)>
        <!ELEMENT i_freetext (#PCDATA)>

=== alvesjnr/opentrials/trunk/opentrials/repository/xml/samples/generated-from-test-otxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE trials SYSTEM "http://ensaiosclinicos.gov.br/xml/opentrials.dtd">
<trials version="1">
    <trial status="published"
           date_registration="2011-01-19"
           created="2011-01-19"
           updated="2011-01-19">
        <trial_identification>
            <trial_id>RBR-9fm6bk</trial_id>
            <utrn_number>None</utrn_number>
            <reg_name>REBEC</reg_name>
            <public_title>A long study about HIV</public_title>
            <acronym>HIV Study</acronym>
            <acronym_expansion>Long HIV Study</acronym_expansion>
            <scientific_title>Full trial: a long study about HIV</scientific_title>
            <scientific_acronym>HIV Study</scientific_acronym>
            <scientific_acronym_expansion>Long HIV Study</scientific_acronym_expansion>
        </trial_identification>

        <sponsors_and_support>
            <primary_sponsor country_code="BR" type="clinical_research_network">
                <name>New name of ACNE</name>
                <address>Av. Goias, 1249, Centro</address>
            </primary_sponsor>

            

            
        </sponsors_and_support>

        <health_conditions>
            
            <hc_code vocabulary="decs" version="" code="C02">
                <text>Virus diseases</text>
                
                
                <text_translation lang="pt-br">Viroses</text_translation>
                
                
            </hc_code>
            

            
            <keyword vocabulary="decs" version="" code="D12.776.124.486.485.114.254.150.440">
                <text>HIV Antibodies</text>
                
                
                <text_translation lang="pt-br">Anticorpos Anti-HIV</text_translation>
                
                
            </keyword>
            

            <freetext>HC free text</freetext>
        </health_conditions>

        <interventions>
            
            <i_code value="drug"></i_code>
            
            <i_code value="device"></i_code>
            

            
            <keyword vocabulary="decs" version="" code="G02.111.570.080.689.330.400">
                <text>HIV Enhancer</text>
                
                
                <text_translation lang="pt-br">Ampliador HIV</text_translation>
                
                
            </keyword>
            

            <freetext>I free text</freetext>
        </interventions>

        <recruitment status="not_yet_recruiting">
            
            <recruitment_country value="BR"></recruitment_country>
            

            <inclusion_criteria>Many criterias we could include here</inclusion_criteria>
            <exclusion_criteria>Male at all</exclusion_criteria>
            <gender value="female"></gender>
            <agemin value="60" unit="years"></agemin>
            <agemax value="5" unit="months"></agemax>

            
            <date_enrolment_actual start="11/2010" end=""></date_enrolment_actual>
            

            <target_size value="3"></target_size>
        </recruitment>

        <study expanded_access_program="no"
               number_of_arms="2">
            <study_design>The study design of this</study_design>
            <type value="interventional"></type>
            <phase value="null"></phase>
            <purpose value="diagnostic"></purpose>
            <intervention_assignment value="single-group"></intervention_assignment>
            <masking value="open"></masking>
            <allocation value="non-randomized-controlled"></allocation>
        </study>

        <outcomes>
            
            <primary_outcome value="Description of outcome 1">
                
            </primary_outcome>
            

            
            <secondary_outcome value="Description of outcome 2">
                
            </secondary_outcome>
            
        </outcomes>

        <contacts>
            
            <person pid="1" country_code="BR">
                <firstname>Tarsila</firstname>
                <middlename>Ribeiro</middlename>
                <lastname>Neiva</lastname>
                <address>Rua Boituva, 449</address>
                <city>Goiania</city>
                <zip>74000-970</zip>
                <telephone>+55(62)4525-1343</telephone>
                <email>tarsila@raminel.com.br</email>
                
                <affiliation country_code="BR" type="clinical_research_network">
                    <name>New name of ACNE</name>
                    <address>Av. Goias, 1249, Centro</address>
                </affiliation>
                
            </person>
            
            <person pid="2" country_code="BR">
                <firstname>Linus</firstname>
                <middlename>Ribeiro</middlename>
                <lastname>Neiva</lastname>
                <address>Rua Boituva, 449</address>
                <city>Goiania</city>
                <zip>74000-970</zip>
                <telephone>+55(62)4525-1343</telephone>
                <email>linus@raminel.com.br</email>
                
                <affiliation country_code="BR" type="clinical_research_network">
                    <name>New name of ACNE</name>
                    <address>Av. Goias, 1249, Centro</address>
                </affiliation>
                
            </person>
            
            <person pid="1" country_code="BR">
                <firstname>Tarsila</firstname>
                <middlename>Ribeiro</middlename>
                <lastname>Neiva</lastname>
                <address>Rua Boituva, 449</address>
                <city>Goiania</city>
                <zip>74000-970</zip>
                <telephone>+55(62)4525-1343</telephone>
                <email>tarsila@raminel.com.br</email>
                
                <affiliation country_code="BR" type="clinical_research_network">
                    <name>New name of ACNE</name>
                    <address>Av. Goias, 1249, Centro</address>
                </affiliation>
                
            </person>
            

            
            <public_contact person="1"></public_contact>
            
            <public_contact person="2"></public_contact>
            
            
            
            <scientific_contact person="1"></scientific_contact>
            

            
        </contacts>

        <secondary_ids>
            
        </secondary_ids>

        <references>
            <link url="/rg/RBR-9fm6bk/v3/"></link>
        </references>

        
        
        
    </trial>
</trials>
